#!/usr/bin/env python
# -*- mode: python; coding: utf-8 -*-
"""
Usage: doomsday [OPTIONS] [YEAR]

Positional arguments:
  YEAR                  year to find doomsday for

Optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show version information and exit
  -c, --copyright       show copying policy and exit
  -r, --reminder        show doomsday algorithm reminder and exit
  -f FORMAT, --format FORMAT
                        date format (default ‘%A’: full weekday name)
"""
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose.  See the GNU General Public License for  #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

# http://python-future.org/quickstart.html#quickstart-guide
from __future__ import print_function, unicode_literals

import sys
import os
import argparse
import datetime

from datetime import (MINYEAR, MAXYEAR)

try:
    from locale import (setlocale, LC_ALL, Error)
    _ = setlocale(LC_ALL, '')
except (ImportError, NameError, Error):
    pass

__author__ = 'Klaus Alexander Seistrup <klaus@seistrup.dk>'
__revision__ = '2020-04-07'
__version__ = '0.0.5 (%s)' % __revision__
__copyright__ = """\
doomsday %s
Copyright © 2015-2020 Klaus Alexander Seistrup <klaus@seistrup.dk>

This is free software; see the source for copying conditions.  There is no
warranty; not even for merchantability or fitness for a particular purpose.

Fork me on Github: https://github.com/kseistrup/doomsday
""" % (__version__,)

REMINDER = """
Doomsday is the last day of February — i.e., February 28 in normal years
and February 29 in leap years.

Even months (April, June, August, October and December): The Nth of month
N is also a doomsday:
  · April 4
  · June 6
  · August 8
  · October 10
  · December 12

Odd months (March, May, July, September, November): Use the mnemonic
“I work from 9-5 at the 7-Eleven”:
  · for the  9th month, doomsday is the  5th
  · for the  5th month, doomsday is the  9th
  · for the  7th month, doomsday is the 11th
  · for the 11th month, doomsday is the  7th

January: Doomsday is January 3rd three years out of four, the non-leap
years, and January 4th only in the fourth year, the years divisible by 4.

For other years and centuries, please consult https://rudy.ca/doomsday.html
"""


def isleap(year):
    """Is <year> a leap year?"""
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)


def die(message=None, exit_code=0):
    """Optionally write a message and exit with an exit code"""
    if message is not None:
        print(message, file=sys.stdout if not exit_code else sys.stderr)
    sys.exit(exit_code != 0)


def doomsday(year=None):
    """Returns last day of february in <year>"""
    if year is None:
        year = datetime.date.today().strftime('%Y')
    if not year.isdigit():
        die('Invalid year: {0}'.format(year), 1)

    year = int(year)

    if year < MINYEAR or year > MAXYEAR:
        die('Year not in range {0}..{1}'.format(MINYEAR, MAXYEAR), 1)

    try:
        dday = datetime.date(year, 2, 29 if isleap(year) else 28)
    except ValueError as error:
        if sys.version_info < (3, 0) and year < 1900:
            print('A year ≥ 1900 is required', file=sys.stderr)
        die('{0}: {1}'.format(str(error).capitalize(), year))

    return dday


def main(progname='doomsday'):
    """Main entry point"""

    parser = argparse.ArgumentParser(
        prog=progname,
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s/' + __version__,
                        help='show version information and exit')
    parser.add_argument('-c', '--copyright', action='version',
                        version=__copyright__,
                        help='show copying policy and exit')
    parser.add_argument('-r', '--reminder', action='version',
                        version=REMINDER,
                        help='show doomsday algorithm reminder and exit')
    parser.add_argument('-f', '--format', default='%A',
                        help='date format (default ‘%%A’: full weekday name)')
    parser.add_argument('YEAR', nargs='?', default=None,
                        help='year to find doomsday for')

    args = parser.parse_args()

    try:
        result = doomsday(args.YEAR).strftime(args.format.strip('"\''))
    except ValueError as error:
        die(str(error).capitalize(), 1)

    print(result)

    return 0


if __name__ == '__main__':
    sys.exit(main(os.path.basename(sys.argv[0])))

# eof
